# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: ^keggtools/|^test/|^docs/(.*).py

    -   id: end-of-file-fixer
        files: ^keggtools/|^test/|^docs/(.*).py

    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

    -   id: detect-private-key

-   repo: local
    hooks:

    # Clear cells in jupyter notebooks
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert ./reproducibility/*.ipynb --ClearOutputPreprocessor.enabled=True --inplace


# add pytest hook
# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         stages: [commit]
#         language: system
#         entry: pytest -p keggtools --show-capture=log
#         types: [python]
#         pass_filenames: false
#         always_run: true



# TODO: add mypy, pylint and coverage hook
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.782
#     hooks:
#     -   id: mypy

