# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: ^keggtools/|^test/|^docs/(.*).py

    -   id: end-of-file-fixer
        files: ^keggtools/|^test/|^docs/(.*).py

    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=2000']

    -   id: detect-private-key

# -   repo: local
#     hooks:

#     # Clear cells in jupyter notebooks
#     -   id: jupyter-nb-clear-output
#         name: Check notebook cells
#         files: \.ipynb$
#         stages: [pre-commit]
#         language: system
#         entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace ./reproducibility/*.ipynb



-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
    # Run the linter.
    -   id: ruff
        types_or: [ python, pyi ]
    # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi ]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.971
#     hooks:
#     -   id: mypy
#         name: Static code analysis
#         files: ^(keggtools|test|docs)/(.*).py
#         additional_dependencies: ["types-requests"]


# add pytest hook
-   repo: local
    hooks:
    -   id: pytest
        name: Run unittest
        stages: [pre-commit]
        language: system
        entry: pytest
        types: [python]
        pass_filenames: false
        always_run: true

