
FROM jupyter/datascience-notebook

LABEL maintainer="harryhaller001"


USER root

# Update ubuntu and install graphviz
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        graphviz \
    && rm -rf /var/lib/apt/lists/*


USER jovyan

# Update pip
RUN pip3 install pip --upgrade

# Install python dependencies
RUN pip3 install scanpy python-igraph louvain leidenalg scikit-learn matplotlib pandas numpy umap-learn

# Set caching dir
ENV KEGG_DATA="/var/data/kegg_data/.caching"

# Set persistance
VOLUME [ "/var/data/kegg_data/.caching" ]

# Install keggtools
RUN pip3 install pydot requests tqdm mygene keggtools==0.3.0

